language: php
php:
  - 7.0
  - 7.1
  - 7.2
sudo: false
services:
  - mysql
  - memcached
  - mongodb
before_install:
  - phpenv config-add tests/config.ini
  - phpenv config-rm xdebug.ini
install:
  - composer install
before_script:
  - mysql -e 'create database fusio;';
script:
  - vendor/bin/phpunit
env:
  - DB=mysql
  - DB=sqlite
